services:
  redis:
    build:
      context: database/redis
      dockerfile: Dockerfile
      args:
        REDIS_VERSION: ${REDIS_VERSION}
    container_name: volcanion-identity-redis
    ports:
      - "6379:6379"
    networks:
      - volcanion-identity-network
    volumes:
      - redis-data:/data
    restart: always

  postgres:
    build:
      context: database/postgresql
      dockerfile: Dockerfile
      args:
        POSTGRES_VERSION: ${PG_VERSION}
        POSTGRES_USER: ${PG_USER}
        POSTGRES_PASSWORD: ${PG_PASSWORD}
        POSTGRES_DB: ${PG_DATABASE}
    container_name: volcanion-identity-postgres
    ports:
      - "5432:5432"
    networks:
      - volcanion-identity-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  volcanion-identity:
    build:
      context: Volcanion_Identity_Presentation/
      dockerfile: DockerfileIn
    container_name: volcanion-identity
    ports:
      - "5000:443"
      - "5001:80"
    networks:
      - volcanion-identity-network
    depends_on:
      - redis
      - postgres
    restart: always

networks:
  volcanion-identity-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
    