// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volcanion.Identity.Models.Context;

#nullable disable

namespace Volcanion.Identity.Presentation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250425121014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.GrantPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RolePermissionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RolePermissionId");

                    b.ToTable("GrantPermissions");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00551060-f0c9-49d8-971e-27f980b8801a"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9233), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "All"
                        },
                        new
                        {
                            Id = new Guid("2aef0e2d-1bae-4761-868b-a132ba4706bf"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9236), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Create"
                        },
                        new
                        {
                            Id = new Guid("69b465af-b54b-4bda-af3d-91d2fde76249"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9241), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Read"
                        },
                        new
                        {
                            Id = new Guid("cdbb5b03-c310-41ef-9aaa-096adb0323dd"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9243), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Update"
                        },
                        new
                        {
                            Id = new Guid("6b714248-6087-4413-9211-cb50c4089650"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9244), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "SoftDelete"
                        },
                        new
                        {
                            Id = new Guid("a100d8d7-1cc0-4eb2-942c-ff27b934a110"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9245), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "HardDelete"
                        },
                        new
                        {
                            Id = new Guid("67e1636a-9864-4cb3-866e-0201835c4df0"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9247), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Grant"
                        });
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c945e0e8-c9a4-4755-bd7a-e8cbc407d5f7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(8946), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("9e8a19fa-31f1-42b4-a114-067e3f29ed13"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9024), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Account"
                        },
                        new
                        {
                            Id = new Guid("9c372f98-a485-4e24-a0d6-7977c9b13b76"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9026), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Role"
                        },
                        new
                        {
                            Id = new Guid("760f1334-050c-4703-82bd-082b55acf97c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9027), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Permission"
                        },
                        new
                        {
                            Id = new Guid("5678ce20-9b79-465b-a52f-db25346dc2ce"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9029), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "RolePermission"
                        },
                        new
                        {
                            Id = new Guid("df040f72-2d19-4299-9c20-62fb586a931c"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 25, 19, 10, 13, 922, DateTimeKind.Unspecified).AddTicks(9030), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "GrantPermission"
                        });
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.GrantPermission", b =>
                {
                    b.HasOne("Volcanion.Identity.Models.Entities.Account", "Account")
                        .WithMany("GrantPermissions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Volcanion.Identity.Models.Entities.RolePermission", "RolePermission")
                        .WithMany("GrantPermissions")
                        .HasForeignKey("RolePermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("RolePermission");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("Volcanion.Identity.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Volcanion.Identity.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Account", b =>
                {
                    b.Navigation("GrantPermissions");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.RolePermission", b =>
                {
                    b.Navigation("GrantPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
