// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volcanion.Identity.Models.Context;

#nullable disable

namespace Volcanion.Identity.Presentation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250421042702_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Avatar")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.GrantPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RolePermissionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RolePermissionId");

                    b.ToTable("GrantPermissions");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f68f9851-84c3-4191-8d81-01433f9c5277"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7566), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "All"
                        },
                        new
                        {
                            Id = new Guid("94a933de-37a9-4539-b00c-1ae7b253fcb3"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7647), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Create"
                        },
                        new
                        {
                            Id = new Guid("f5ce26f7-d1b4-4a5c-9f88-48c1cd025eeb"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7650), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Read"
                        },
                        new
                        {
                            Id = new Guid("e0c2db33-56cc-42d0-bb00-c42411492a4b"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7652), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Update"
                        },
                        new
                        {
                            Id = new Guid("bb1be038-efdc-4089-b818-f270f749f73d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7654), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "SoftDelete"
                        },
                        new
                        {
                            Id = new Guid("d34cf9c6-8a97-4cf5-aaf8-68c4e9949f6d"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7660), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "HardDelete"
                        },
                        new
                        {
                            Id = new Guid("99b51ee3-e78b-4c4d-9d24-685d193b18d9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7672), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Grant"
                        });
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5143ea64-edd7-42f0-bf70-7168f93e8c97"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7338), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("ba9b27cf-3186-4495-9a65-c2711b545634"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7374), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Account"
                        },
                        new
                        {
                            Id = new Guid("b48a42ee-61ef-46fb-8e0e-9a1b5be5195f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7376), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Role"
                        },
                        new
                        {
                            Id = new Guid("7747afba-eb22-4c2b-a465-937745b5953f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7391), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "Permission"
                        },
                        new
                        {
                            Id = new Guid("582cdad6-0e24-4cb4-8298-357084ab4b22"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7393), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "RolePermission"
                        },
                        new
                        {
                            Id = new Guid("d667e0f0-5313-46c1-ada4-a1d1bcb79d36"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 4, 21, 11, 26, 58, 687, DateTimeKind.Unspecified).AddTicks(7395), new TimeSpan(0, 7, 0, 0, 0)),
                            IsActived = true,
                            IsDeleted = false,
                            Name = "GrantPermission"
                        });
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActived")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.GrantPermission", b =>
                {
                    b.HasOne("Volcanion.Identity.Models.Entities.Account", "Account")
                        .WithMany("GrantPermissions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Volcanion.Identity.Models.Entities.RolePermission", "RolePermission")
                        .WithMany("GrantPermissions")
                        .HasForeignKey("RolePermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("RolePermission");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.RolePermission", b =>
                {
                    b.HasOne("Volcanion.Identity.Models.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Volcanion.Identity.Models.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Account", b =>
                {
                    b.Navigation("GrantPermissions");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Volcanion.Identity.Models.Entities.RolePermission", b =>
                {
                    b.Navigation("GrantPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
